### ISSUE TITLE
npm warnings

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#74] opened 2014-11-11 18:56 UTC
Installing from the `develop` branch I get the following warnings. Are they meaningful?

```
npm WARN package.json marklogic-8-ea-examples@0.0.0 No description
npm WARN package.json marklogic-8-ea-examples@0.0.0 No repository field.
npm WARN package.json marklogic-8-ea-examples@0.0.0 No README data
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"1.4.23"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"1.4.23"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"1.4.23"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"1.4.23"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"1.4.23"})
```

The last 5 look out of our control.

**Comment by ehennum** [comment] 2015-01-12 01:00
I reproduced the message.

winston has the dependency on hawk, which has the dependency on boom, cryptiles, hoek, sntp

I assume that winston would have upgraded or replaced hawk if it were easy to do so, so I think we probably have to live with the issue for now.  If you agree, let's close the issue instead of kicking it down the road.

**Comment by ehennum** [comment] 2015-04-10 01:48
closing because shipped

**Closed by ehennum** 2015-04-10 01:48 UTC
Labels: aesthetic, Bug, closed
