### ISSUE TITLE
Read binary chunk is failing in Windows environment

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#160] opened 2015-03-31 09:33 UTC
Build : 8.0-20150330

Code snippet : 
************************************************
  it('should read the binary in chunk', function(done){
    this.timeout(10000);
    var uri = '/test/write/somePdfFile.pdf';
    dbReader.documents.read(uri).stream('chunked').
    on('data', function(data) {
      var strData = data.toString();
      strData.should.containEql('CVISION Technologies');
      }).
    on('end', function() {
      done();
    }, done);   
  });
************************************************

The output can be checked on below mentioned uri : https://regression-status.marklogic.com/new-app/space2/diff-archive/genesis/b8_0/2015-03-30/winnt-64-w7genesis/diffs/Binary_documents_test_-1110242714.xml

**Comment by ehennum** [comment] 2015-03-31 16:06
I need to be able to reproduce the issue.  

Is this the test-complete/nodejs-documents-read-chunk.js test case?  If not, can you attach the data and instructions on how to reproduce the issue?

I do have a concern with the test-complete/nodejs-documents-read-chunk.js test case because it assumes the string will always be in the same chunk, which is not guaranteed.  The string could be split across chunks, which would cause a spurious failure.

**Comment by MayankBhatnagar89** [comment] 2015-03-31 16:11
Yes Erik this test is the same test-complete/nodejs-documents-read-chunk.js and it is failing only on windows environment and passing successfully on Linux and Mac

**Comment by ehennum** [comment] 2015-03-31 16:14
Also, if the data file is test-complete/data/somePdfFile.pdf, I notice that the phrase "CVISION Technologies" only appears in the metadata for the PDF file and not the content.

It could be failing on Windows because the "CVIS" ends up in one chunk and "ION Technologies" ends up in another chunk.  That would not be a bug -- chunks are not guaranteed to be the same on different platforms or even different runs.

It could also be failing because the server doesn't include the metadata in the binary range on Windows.

**Comment by ehennum** [comment] 2015-03-31 16:15
Is the server on Windows or just the Node.js client?

**Comment by MayankBhatnagar89** [comment] 2015-03-31 17:01
The server and the client both are Windows 7 here.

**Comment by ehennum** [comment] 2015-03-31 17:04
If I can remote desktop into the client, please add the connection information to the internal BugTrak record.

**Comment by ehennum** [comment] 2015-03-31 17:29
Or, you could email the connection information to me.  

One other question is whether the same test ran successfully on Windows previously.

**Comment by ehennum** [comment] 2015-03-31 18:33
I suspect there is probably an environmental issue with the test case and not with the product.

I installed MarkLogic and the Node.js API on Windows 7, and the regression test ran green under cygwin.

**Comment by gvaidees** [comment] 2015-04-01 21:11
@MayankBhatnagar89 I am also seeing the runs on Jenkins as being successful for both test-basic and test-complete

http://engrlab-128-157.engrlab.marklogic.com:8080/

**Comment by ehennum** [comment] 2015-04-02 23:03
Closing for now -- we should reopen if we find a way to reproduce this issue.

**Closed by ehennum** 2015-04-02 23:03 UTC
Labels: Bug, major, verify
