### ISSUE TITLE
multi-statement txn throw warning saying .then() only accepts functions but was passed: [object Undefined], [object Undefined]

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#168] opened 2015-05-26 22:16 UTC
This started happening after I upgraded to ```1.0.2```
```
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at Operation.operationResultPromise (/Users/sreddy/space/angularjs/BugTrack/node_modules/marklogic/lib/mlrest.js:1571:18)
    at Object.callBackMethod [as result] (/Users/sreddy/space/angularjs/BugTrack/node_modules/marklogic/lib/mlutil.js:132:17)
    at Object.exports.remove [as handle] (/Users/sreddy/space/angularjs/BugTrack/server/api/user/user.controller.js:128:28)
    at next_layer (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/route.js:107:5)
    at /Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:195:24
    at param (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:268:14)
    at param (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:280:16)
    at Function.proto.process_params (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:296:3)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at Function.proto.handle (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:234:5)
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at Operation.operationResultPromise (/Users/sreddy/space/angularjs/BugTrack/node_modules/marklogic/lib/mlrest.js:1571:18)
    at Object.callBackMethod [as result] (/Users/sreddy/space/angularjs/BugTrack/node_modules/marklogic/lib/mlutil.js:132:17)
    at /Users/sreddy/space/angularjs/BugTrack/server/api/user/user.controller.js:134:12
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at Object.exports.remove [as handle] (/Users/sreddy/space/angularjs/BugTrack/server/api/user/user.controller.js:130:8)
    at next_layer (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/route.js:107:5)
    at /Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:195:24
    at param (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:268:14)
    at param (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:280:16)
    at Function.proto.process_params (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:296:3)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at Function.proto.handle (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:234:5)
    at Layer.router (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:23:12)
    at trim_prefix (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:226:17)
    at /Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:198:9
    at Function.proto.process_params (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at Operation.operationResultPromise (/Users/sreddy/space/angularjs/BugTrack/node_modules/marklogic/lib/mlrest.js:1571:18)
    at Object.callBackMethod [as result] (/Users/sreddy/space/angularjs/BugTrack/node_modules/marklogic/lib/mlutil.js:132:17)
    at /Users/sreddy/space/angularjs/BugTrack/server/api/user/user.controller.js:140:12
    at processImmediate [as _immediateCallback] (timers.js:358:17)
From previous event:
    at Object.exports.remove [as handle] (/Users/sreddy/space/angularjs/BugTrack/server/api/user/user.controller.js:135:8)
    at next_layer (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/route.js:107:5)
    at /Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:195:24
    at param (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:268:14)
    at param (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:280:16)
    at Function.proto.process_params (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:296:3)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at Function.proto.handle (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:234:5)
    at Layer.router (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:23:12)
    at trim_prefix (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:226:17)
    at /Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:198:9
    at Function.proto.process_params (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:251:12)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:189:19)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
    at next (/Users/sreddy/space/angularjs/BugTrack/node_modules/express/lib/router/index.js:166:38)
```

_my code_
```javascript
exports.remove = function(req, res) {
    res.locals.errors = req.flash();
    var uri = '/users/' + req.params.username + '.json'
    var transactionId = null;
    db.transactions.open().result().then(function(response) {
        transactionId = response.txid
    }).then(function() {
        return db.documents.remove({
            uri: uri,
            txid: transactionId
        }).result();
    }).then(function() {
        return db.documents.patch({
            uri: 'config.json',
            operations: [p.remove("/users[username eq '" + req.params.username + "']")],
            txid: transactionId
        }).result()
    }).then(function() {
        return db.transactions.commit(transactionId).result(function() {
            return res.status(200).json({
                message: 'Removed user'
            });
        }, function(error) {
            return res.status(error.statusCode).json(error.body.errorResponse)
        });
    }).catch(function(error) {
        db.transactions.rollback(transactionId);
        console.log(JSON.stringify(error, null, 2));
        return res.status(error.statusCode).json(error);
    });
};
```

**Comment by ayuwono** [comment] 2015-05-26 22:29
Looks similar with:
https://github.com/marklogic/node-client-api/issues/162

Do you have this line?
process.env.NODE_ENV = 'development';

**Comment by csreddy** [comment] 2015-05-26 22:36
Yes. I have like this ```process.env.NODE_ENV = process.env.NODE_ENV || 'development';```

**Comment by ehennum** [comment] 2015-05-27 16:55
Hi, Sudhakar:  This bug should be fixed in 8.0-3. Please try with the development branch and close this bug if you no longer see it.

**Comment by csreddy** [comment] 2015-06-01 06:57
I have 8.0-2 currently.  I'll try on 8.0-3 and close it if I can't reproduce.

**Comment by csreddy** [comment] 2015-06-12 21:48
Works fine with node 0.10.26 (as required by the apis) & 8.0-3. With 0.12.x and I saw the errors happening even with 8.0-3. Is this known?

**Comment by ehennum** [comment] 2015-06-12 21:54
The Node.js API stipulates 0.10.26 as the oldest supported version.  Any version less than 0.11 should be supported.

We aren't supporting io.js or Node.js 0.12 for production deployments because both will be unstable until sometime after the two version streams merge.

But, we certainly want to know whether the API works on io.js and Node.js 0.12.  When we last checked, the unit and regression tests all passed on both io.js and Node.js 0.12

Anyway, I'll see if I can reproduce the issue on 0.12 with the master branch.

**Comment by ehennum** [comment] 2015-06-12 22:58
I'm not able to reproduce this issue on Node.js 0.12.4 using the 8.0-3 release of the Node.js API and the current dependencies specified for the Node.js API.

Specifically, I tested the following (which used to trigger the issue in Bluebird)

    NODE_ENV=development node examples/read-documents.js

Can you provide a concise test case that reproduces the issue on Node.js 0.12.4?

**Comment by csreddy** [comment] 2015-06-15 17:19
I cannot reproduce in my app or in an isolated test case anymore. I'll keep an eye on it. You can close this for now. Thanks!

**Closed** 2015-06-15 17:20 UTC
Labels: Bug, major, new
