### ISSUE TITLE
.suggest() response data

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#368] opened 2017-02-13 10:02 UTC
Given a few sample documents in the datababase

```json
{ "name": "Darth Vader" }
{ "name": "Darth Sidious" }
```

And the following sample code:

```javascript
db.documents.suggest('a darth',
  qb.where(
    qb.collection('characters'),
    qb.parsedFrom('',
      qb.parseBindings(
        qb.range('name', qb.bindDefault())
      )
    )
  )
  .slice(0, 30)
).result().then(data => console.log(data));
```

Why does the response have the following format:

```javascript
[ 'a "Darth Sidious"', 'a "Darth Vader"' ]
```

For a suggestion of `a darth` I'd expect 0 results. Why do I get the 'a' appended to the response?

For a a suggestion of `darth`, I'd expect to see:

```javascript
[ 'Darth Sidious', 'Darth Vader' ]
```

but why do I still get the extra quotes?

```javascript
[ '"Darth Sidious"', '"Darth Vader"' ]
```

What's their purpose?

**Comment by jmakeig** [comment] 2017-02-15 18:45
I think the issue is that `suggest()` is aware of the query string. It’s not just a lexicon look-up. @wooldridge, can you confirm, please?

**Comment by wooldridge** [comment] 2017-09-07 01:27
I discussed this with @ehennum. 

If the search string passed into the suggest method has multiple words (as this one does -- "a" and "darth"), only the last word is used to find matches. That is why the wildcard search returns the two matches, neither of which include "a".

If the match is a multiword phrase, the match text is included in the resulting suggestions with quotes. (So if you had a document with `{ name: "Darth" }`, that would yield an 'a Darth' suggestion (no additional quotes).) The method is producing suggestions that can be fed into documents.query() as described in:

https://docs.marklogic.com/guide/node-dev/search#id_27613

**Comment by wooldridge** [comment] 2017-09-07 01:31
Closing since this is not a bug. `suggest()` is performing consistent with the REST equivalent. For lexicon lookups, you can look at `cts:value-match` on the server, although this isn't currently exposed through REST or the Node.js client.

**Closed by wooldridge** 2017-09-07 01:31 UTC
Labels: Bug, minor, new
