### ISSUE TITLE
Optic planBuilder test failures 

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#463] opened 2017-11-16 18:32 UTC
In running tests in preparation for upgrading the Node.js version, I'm seeing Optic planBuilder test failures when running both Node.js versions 6.5.0 and 6.9.0. I have the latest MarkLogic server build. The failures are in the following test files:

- test-basic/plan-composers.js
- test-basic/plan-views.js

Here is the output:

```
  1) composers for literals with except:

      AssertionError: expected 2 to be 1
      + expected - actual

      -2
      +1
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at test-basic/plan-composers.js:291:33
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  2) view composers with except:

      AssertionError: expected 6 to be 4
      + expected - actual

      -6
      +4
      
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value (node_modules/should/cjs/should.js:356:19)
      at test-basic/plan-views.js:444:31
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by ehennum** [comment] 2017-11-17 03:03
I was on 6.10, but I downgraded to the earliest version of 6.9, and I'm still not seeing any errors with plan-*.js.  I'll try a fresh clone and fresh database once I've checked in other fixes that are in flight.

**Comment by wooldridge** [comment] 2017-11-17 18:39
On my Mac, did a fresh build of my MarkLogic server: 10.0-20171117

Using Node.js version 6.9.0 with a fresh "npm install" on the develop branch, I'm still seeing those two errors when I run the test-basic tests on my local machine.

**Comment by ayuwono** [comment] 2017-11-17 18:49
It might be on the plan level/server issue. The SJS Optic regression tests are failing on except too:
https://bugtrack.marklogic.com/48378

**Comment by ehennum** [comment] 2017-11-18 04:53
Okay, after a rebuild, I am able to reproduce the errors for 

*  composers for literals with except
*  view composers with except

There is a known server bug with except that, I believe, is the root cause.  When that bug is fixed, this bug should go away.

By the way, I still get errors for:

*  point-in-time with timestamp graphs read default graph should set and use timestamp
*  point-in-time with timestamp graphs sparql query should set and use timestamp

**Comment by ehennum** [comment] 2017-11-20 00:36
The fix committed to internal issue 48378 on Saturday resolved the problem in my testing.  If you're no longer seeing the issue, please close the bug.

**Comment by ayuwono** [comment] 2017-11-20 17:38
Verified passed on regression 11/19

**Closed by ayuwono** 2017-11-20 17:38 UTC
Labels: Bug, major, ship

**Comment by wooldridge** [comment] 2017-11-20 18:45
I'm no longer seeing those two errors on my test-basic tests with the new sever updates.
