### ISSUE TITLE
db.documents.probe() in transaction causes forest to go into 'middle-closing' state

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#254] opened 2016-07-09 08:15 UTC
To reproduce run this test, after running this test, the forest goes into `middle closing` state.
Server must be restarted to reset forest state

``` javascript
  it('should probe with txid', function(done) {
    this.timeout(10000);
    var tid = null;
    db.transactions.open().result().
    then(function(response) {
      tid = response.txid;
      return db.documents.probe({uri: '/test/doc1.json', txid: tid}).result();
    }).
    then(function(response) {
      done();
    });  
  });
```

in error log

```
2016-07-09 01:03:23.010 Debug: Retrying AppRequestTask::handleEvalLocked 257165224636807238 Query 1 because XDMP-FORESTNOT: Forest unittest-nodeapi-1 not available: middle closing
2016-07-09 01:03:23.131 Debug: Retrying AppRequestTask::handleEvalLocked 257165224636807238 Query 2 because XDMP-FORESTNOT: Forest unittest-nodeapi-1 not available: middle closing
2016-07-09 01:03:23.407 Debug: Retrying AppRequestTask::handleEvalLocked 257165224636807238 Query 3 because XDMP-FORESTNOT: Forest unittest-nodeapi-1 not available: middle closing
```

**Comment by wooldridge** [comment] 2017-02-01 06:01
@csreddy, I can't reproduce this bug. I've tried various combinations of API (develop, 1.0-develop, master, 1.0-master) and ML (8.0-6, 9.0-ea4, trunk) versions. Do you recall the environment you were using?

**Comment by csreddy** [comment] 2017-02-01 06:44
Sorry, it was a long time ago. It could be 8.0.x build, that's all I remember

**Comment by wooldridge** [comment] 2017-02-02 02:22
Since I can't reproduce this and I'm not seeing this issue in my work on another probe() issue: 

https://github.com/marklogic/node-client-api/issues/255

I'm confident this is no longer an issue and am closing.

**Closed by wooldridge** 2017-02-02 02:22 UTC
Labels: Bug
