### ISSUE TITLE
Fix eval test with date data type.

### ISSUE THREAD

**Issue by georgeajit** [marklogic/node-client-api#537] opened 2020-01-22 23:30 UTC
This test fails on nightly Jenkins test runs.

```server-side call to eval JavaScript.should generate a date value```

Stacktrace
expected 2010-10-08 17:17:15.125 -0700 to equal 2010-10-08 10:17:15.125 -0700

      + expected - actual

      -[Date: 2010-10-09T00:17:15.125Z]
      +[Date: 2010-10-08T17:17:15.125Z]
      
```
AssertionError: expected 2010-10-08 17:17:15.125 -0700 to equal 2010-10-08 10:17:15.125 -0700
    at Assertion.fail (node_modules/should/cjs/should.js:275:17)
    at Assertion.value (node_modules/should/cjs/should.js:356:19)
    at /space/jenkins/workspace/NodeAPIUnitTests_develop-b10_0/test-basic/server-exec.js:109:32
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```
Used QConsole to execute this snippet ```eval('new Date("2010-10-08T10:17:15.125");')``` . The result from QConsole run is ```2010-10-08T17:17:15.125```.

**Comment by ehennum** [comment] 2020-01-31 17:20
I believe the root cause is that the server should serialize JavaScript Date values with the toISOString() method.  See internal server bug 54293.

**Comment by ehennum** [comment] 2020-04-24 23:43
fixup should make unit test green despite timezone differences on client and server

**Comment by georgeajit** [comment] 2020-04-30 22:47
This issue was supposed to have a MarkLogic server side fix (in 10.0.4 or later). But as of now, PM decides that fix won't be happening and hence there is a need for workaround for these test failures.

**Comment by ehennum** [comment] 2020-04-30 22:49
@georgeajit , I take it from the reassignment that the fix checked in last Friday didn't solve the issue in the Jenkins environment.

**Comment by georgeajit** [comment] 2020-05-01 00:01
On Jenkins I see these two tests failing (Note: diff tests than original reported ones):
point-in-time with timestamp graphs read default graph.should set and use timestamp
point-in-time with timestamp graphs sparql query.should set and use timestamp

I also see alternate builds (Jenkins jobs ) passing and failing.

**Comment by georgeajit** [comment] 2020-05-01 00:02
This build passed: https://jenkins.marklogic.com/view/Node%20API/job/NodeAPIUnitTests_develop-b10_0/648/

And this build failed: 
https://jenkins.marklogic.com/view/Node%20API/job/NodeAPIUnitTests_develop-b10_0/647/

**Comment by ehennum** [comment] 2020-05-07 23:25
This test bug had a root cause different from the issue of timezone loss on the default Date serialization.

The test was trying to choose a timestamp before the documents were created by subtraction.  If the timing between the document creation and the query happened to be to larger than the subtracted number, the documents would be matched.

Now, the test writes a document before any test is run and uses the timestamp for that document as the timestamp before document creation.

That seems to work and has the added benefit that we can get rid of the big-integer dependency. I noticed that a complete test had an unused dependency on that package and removed that dependency.

Removing the big-integer dependency shouldn't cause any regressions and, if the hypothesis is correct, the timestamp tests should run green in the Jenkins environment as they do locally.

**Closed** 2020-11-16 17:04 UTC
Labels: Bug, minor, ship
