### ISSUE TITLE
Inconsistent count for batch load

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#284] opened 2016-08-24 20:29 UTC
Hi,

Give the following sample code taken from [the examples](https://github.com/marklogic/node-client-api/blob/8f63f6b531258c733be3ff0e9a992fcd7d444f37/examples/before-load.js) I have experienced the following behaviour.

I have updated the above code in the following way:

``` javascript
// I have added a counter -->
var batchSize = 100;
var counter = 0; //added a counter
// I then increase the counter -->
db.documents.write(buffer).result(function(response) {
        console.log(
            'done loading:\n'+
            response.documents.map(function(document) {
              counter++; //increasing the counter here
              return document.uri;
              }).join(', ')+'\n'
            );
        writeBatch(filenames, i + 1);
// and finally print out some debug info:
function writeBatch(filenames, batchFirst) {
  if (batchFirst >= filenames.length) {
    console.log('filenames.length ==> ', filenames.length); //print filenames.length
    console.log('counter ==> ', counter); //print counter
    console.log('done loading example data to');
```

Interestingly each time I execute the code I get different results:

``` bash
$ node before-load.js
filenames.length ==>  261
counter ==>  259
$ node before-load.js
filenames.length ==>  261
counter ==>  261
$ node before-load.js
filenames.length ==>  261
counter ==>  260
```

As you can see the counter gives a different value after each execution.

To debug this further I have reduced the number of documents in the data folder to have only 21 documents and reduced the batch size to be 10. This is what has happened:

``` bash
$ node before-load.js
loading example data
loading batch from /countries/aa.json to ao.json
done loading:
/countries/aa.json, /countries/ae.json, /countries/ac.json, /countries/af.json, /countries/ag.json, /countries/aj.json, /countries/al.json, /countries/am.json, /countries/an.json, /countries/ao.json

loading batch from /countries/as.json to bb.json
done loading:
/countries/as.json, /countries/ar.json, /countries/at.json, /countries/aq.json, /countries/au.json, /countries/av.json, /countries/ax.json, /countries/ay.json, /countries/bb.json

loading batch from /countries/bc.json to bc.json
done loading:
/countries/bc.json

filenames.length ==>  21
counter ==>  20
done loading example data
```

The file `ba.json` is missing - and it hasn't been loaded.

Second time executing the same command:

``` bash
$ node before-load.json
loading example data to
loading batch from /countries/aa.json to ao.json
done loading:
/countries/aa.json, /countries/ac.json, /countries/ae.json, /countries/aj.json, /countries/af.json, /countries/ag.json, /countries/al.json, /countries/am.json, /countries/an.json, /countries/ao.json

loading batch from /countries/ar.json to bb.json
done loading:
/countries/ar.json, /countries/at.json, /countries/as.json, /countries/aq.json, /countries/au.json, /countries/av.json, /countries/ax.json, /countries/ay.json, /countries/ba.json, /countries/bb.json

loading batch from /countries/bc.json to bc.json
done loading:
/countries/bc.json

filenames.length ==>  21
counter ==>  21
done loading example data to
```

As you can see 'ba.json' has now been loaded - we now have all the files loaded.

And for the third iteration:

``` batch
$ node before-load.js
loading example data
loading batch from /countries/aa.json to ao.json
done loading:
/countries/aa.json, /countries/ac.json, /countries/af.json, /countries/ag.json, /countries/ae.json, /countries/aj.json, /countries/am.json, /countries/al.json, /countries/ao.json

loading batch from /countries/aq.json to bb.json
done loading:
/countries/aq.json, /countries/as.json, /countries/ar.json, /countries/at.json, /countries/au.json, /countries/av.json, /countries/ax.json, /countries/ay.json, /countries/ba.json, /countries/bb.json

loading batch from /countries/bc.json to bc.json
done loading:
/countries/bc.json

filenames.length ==>  21
counter ==>  20
done loading example data
```

Now we are missing `an.json`.

I think there's some sort of a race condition that skips a file (or a set of files when the dataset is larger) every now and then. I will keep on investigating but I thought I'd open this issue as well.

**Comment by ehennum** [comment] 2016-08-29 18:04
Have you confirmed that the documents are actually missing in the database?

I'm wondering if this might be a case where -- because the order of the response callback execution is indeterminate -- the last batch might be finishing before the counter reflects one of the previous batches.

**Comment by tpiros** [comment] 2016-08-29 20:53
Yes, @ehennum I did - I'm sorry I forgot to mention that. The counter value would always represent the document count in the database. (I did clear the database before each test load).

**Comment by ehennum** [comment] 2016-08-29 20:58
Hmm, so to state it another way, sometimes before-load.js puts the database in a state where some of the sample documents are missing.

**Comment by tpiros** [comment] 2016-08-29 20:59
That is a correct statement Erik. I will send you an email with actual screenshots but it's effectively some "photographic" evidence of what I have described above.

**Comment by wooldridge** [comment] 2017-10-31 00:11
Appears that the full number of document descriptors in a batch are not being added to the buffer array. Adding the following:

```
    if (isLast) {
      console.log('loading batch from '+buffer[0].uri+' to '+filename);
      console.log('num files: ' + buffer.length);
      db.documents.write(buffer).result(function(response) {
```

we see the buffer length is shorter than expected when documents are missing, e.g. 99 when it should be 100. So in the error case for the example code, files are not being written to begin with.

**Comment by wooldridge** [comment] 2017-10-31 02:53
Fixed by using Promise.all(), which will wait for all batch files to be read before executing a db.documents.write() for that batch.

This fix does not impact any library code, just the file-loading code in the examples. No QA or docs work required for this.

**Closed** 2017-10-31 02:54 UTC
Labels: Bug, major, ship
