### ISSUE TITLE
Setting optimistic locking throws XDMP-UPDATEFUNCTIONFROMQUERY:

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#201] opened 2015-09-16 18:23 UTC
Not sure what I'm doing wrong. Here's what my code looks like:

``` javascript
'use strict';

var fs = require('fs');
var flash = require('connect-flash');
var marklogic = require('marklogic');
var conn = require('../../config/db-config.js').connection;
var db = marklogic.createDatabaseClient(conn);
var q = marklogic.queryBuilder;
var p = marklogic.patchBuilder;
var async = require('async');
var request = require('request');
var _ = require('lodash');
var common = require('../common/common.controller');
var Notify = require('../../email/email').Notify;

var notify = new Notify();

// enable optimistic locking, with version-optional
// this is required to maintain integrity of nextid document
db.config.serverprops.write({
    'update-policy': 'version-optional'
})
    .result(function(response) {
        console.log('setting optimistic locking....');
        console.log(JSON.stringify(response));
    }).catch(function(error) {
        console.log('OPTMISTIC LOCK ERROR', error);
    });


// Get list of items
exports.index = function(req, res) {
    res.send([]);
};
...
...
...
```

error:

```
OPTMISTIC LOCK ERROR { [Error: write REST server properties: cannot process response with 500 status]
  message: 'write REST server properties: cannot process response with 500 status',
  statusCode: 500,
  body:
   { errorResponse:
      { statusCode: 500,
        status: 'Internal Server Error',
        messageCode: 'INTERNAL ERROR',
        message: 'XDMP-UPDATEFUNCTIONFROMQUERY: xdmp:apply(function() as item()*) -- Cannot apply an update function from a query . See the MarkLogic server error log for further detail.' } } }
```

**Comment by csreddy** [comment] 2015-10-13 20:43
This is happening only on Mac. On Linux its fine.

**Comment by ehennum** [comment] 2015-10-13 20:54
Does the user have rest-admin privileges?

**Comment by csreddy** [comment] 2015-10-13 20:56
Yes

**Comment by ehennum** [comment] 2015-10-13 20:57
Both MarkLogic server and Node.js client are on the Mac?

**Comment by csreddy** [comment] 2015-10-13 20:57
Yes

**Comment by ehennum** [comment] 2015-10-13 20:57
Apparently, this is a REST API bug on the Mac.

**Comment by wooldridge** [comment] 2017-02-08 05:26
I can't reproduce, this is working for me:
```
var marklogic = require('marklogic');

var db = marklogic.createDatabaseClient({
  host: 'localhost',
  port: 8000,
  authType: 'digest',
  user: 'admin',
  password: 'admin'
});

db.config.serverprops.write({'update-policy': 'version-required'})
  .result()
  .then(function (response) {
    console.log(response); //returns true
  })
  .catch(function (err) {
    console.log(err);
  });
```
Closing this issue.

**Closed by wooldridge** 2017-02-08 05:26 UTC
Labels: Bug, minor, verify
